# Generated by Django 4.2.6 on 2023-10-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/site_setting', verbose_name='لوگوی سایت')),
                ('team_name', models.CharField(max_length=150, verbose_name='نام تیم')),
                ('copyright_text', models.TextField(verbose_name='متن کپی رایت')),
                ('team_description', models.TextField(verbose_name='توضیحات درباره تیم')),
            ],
        ),
    ]
