# Generated by Django 4.2.6 on 2023-10-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات اصلی سایت', 'verbose_name_plural': 'تنظیمات اصلی سایت'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_main_setting',
            field=models.BooleanField(default=False, verbose_name=' تنظیم بعنوان تنظیمات اصلی سایت'),
        ),
    ]
