# Generated by Django 4.2.6 on 2023-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0003_remove_sitesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/site_setting', verbose_name='لوگوی سایت'),
        ),
    ]
