# Generated by Django 4.2.6 on 2023-10-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_Module', '0004_sitesetting_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/site_setting', verbose_name='لوگوی سایت'),
        ),
    ]
