# Generated by Django 4.2.6 on 2023-10-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Module', '0002_article_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_title',
            field=models.CharField(max_length=400, null=True, verbose_name='عنوان در url'),
        ),
    ]
