# Generated by Django 4.2.6 on 2023-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article_Module', '0005_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_title',
            field=models.CharField(max_length=400, unique=True, verbose_name='عنوان در url'),
        ),
    ]
