# Generated by Django 4.2.6 on 2023-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0002_user_is_dev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_dev',
            field=models.BooleanField(default=False, help_text='نشان میدهد چه کسانی این سایت را طراحی کرده اند', verbose_name='توسعه دهنده سایت'),
        ),
    ]
