# Generated by Django 4.2.6 on 2023-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0005_alter_user_is_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(help_text='مشخص کننده مهارت توسعه دهنده است', max_length=300, verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='field',
            field=models.CharField(blank=True, help_text='مشخص میکند کاربر توسعه دهنده در چه فیلدی مشغول کار است', max_length=500, null=True, verbose_name='فیلد کاری'),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_skills', to='Account_Module.developerskills', verbose_name='مهارت ها'),
        ),
    ]
