# Generated by Django 4.2.6 on 2023-10-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Module', '0009_remove_developerskills_user_developerskills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.DeleteModel(
            name='DeveloperSkills',
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.TextField(blank=True, null=True, verbose_name='مهارت ها'),
        ),
    ]
